/**
 * DownloadBar — compact strip under the preview that triggers CAD file
 * generation via the proxy's /api/download orchestrator.
 *
 * Per-format button states:
 *   idle       default        → click to request
 *   busy       spinner        → request in flight
 *   done       check + status → file started downloading; shows cached?/size/ms
 *   error      ⚠ + tooltip    → hover/click to retry
 *
 * Formats are split into two rows:
 *   [ Local ]       STEP · DXF · IGES     (generated by the in-process worker)
 *   [ Exchanger ]   DWG · IPT · SLDPRT · Z3   (Phase 2 — shows "준비 중" tooltip)
 *
 * Warning banner reminds the user STEP/DXF geometry is final (no feature
 * history). Matches the concept-doc recommendation that parameter edits
 * aren't possible and the workflow is "re-download on spec change".
 */
import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import {
  AlertCircle,
  AlertTriangle,
  Check,
  Download,
  FileDown,
  Loader2,
  RotateCcw,
  Zap,
} from 'lucide-react';

import { getPartApi } from '@/services/api/factory';
import { useSelectionStore } from '@/store/selectionStore';
import type { DownloadFormat, DownloadResult, PartSpec } from '@/types';
import { determineControlType } from '@/utils/controlType';
import { cn } from '@/utils/cn';

/**
 * Collect the user's current EDITBOX / LISTBOX / COMBOBOX / RADIO
 * selections into an `extraDimensions` overlay sent to /download.
 *
 * Why both kinds?
 *   - EDITBOX values (e.g. "전체길이") are the raw number the user typed.
 *     The DB row doesn't store per-selection length, so we MUST send it.
 *   - COMBOBOX/LISTBOX/RADIO values (e.g. "사이즈: M10") are usually
 *     already covered by the DB row's key_values, but we send the
 *     resolved display name anyway in case the generator's alias map
 *     prefers it (it does not override since backend merge order puts
 *     extraDimensions last — they win).
 */
function collectExtraDimensions(
  spec: PartSpec | null,
  specOptions: Record<number, string>,
): Record<string, number | string> {
  const out: Record<string, number | string> = {};
  const series = spec?.series?.[0];
  if (!series) return out;
  for (const opt of series.options) {
    if (!opt.isActive) continue;
    const name = (opt.name ?? '').trim();
    if (!name) continue;
    const kind = determineControlType(opt.type);
    const raw = specOptions[opt.id] ?? opt.defaultValue ?? '';

    if (kind === 'EDITBOX' || kind === 'R_EDITBOX') {
      // User-typed numeric value. Skip empty / zero defaults.
      if (raw === '' || raw == null) continue;
      const n = Number(raw);
      if (!Number.isNaN(n) && n > 0) out[name] = n;
    } else if (kind === 'COMBOBOX' || kind === 'LISTBOX' || kind === 'RADIO') {
      // Resolve enumid → value.name so the backend can alias-match.
      const val = opt.values.find((v) => String(v.enumid) === String(raw));
      if (val?.name) out[name] = String(val.name);
    }
    // CHECKBOX: boolean-ish, not a dimension. Skip.
  }
  return out;
}

// Formats grouped by backend. Order matters — shown left-to-right.
// IGES isn't yet implemented locally, so it sits in the "exchanger/
// pending" row until the writer lands.
const LOCAL_FORMATS: DownloadFormat[] = ['STEP', 'DXF'];
const EXCHANGER_FORMATS: DownloadFormat[] = ['IGES', 'DWG', 'IPT', 'SLDPRT', 'Z3'];

type BtnState =
  | { kind: 'idle' }
  | { kind: 'busy' }
  | { kind: 'done'; result: DownloadResult }
  | { kind: 'error'; message: string; notConfigured?: boolean };

export function DownloadBar() {
  const { t } = useTranslation();
  const partCode = useSelectionStore((s) => s.partCode);
  const dimension = useSelectionStore((s) => s.dimension);
  const spec = useSelectionStore((s) => s.spec);
  const specOptions = useSelectionStore((s) => s.specOptions);
  const [states, setStates] = useState<Partial<Record<DownloadFormat, BtnState>>>({});

  async function trigger(format: DownloadFormat) {
    if (!partCode || !dimension) return;
    setStates((s) => ({ ...s, [format]: { kind: 'busy' } }));
    try {
      const res = await getPartApi().download({
        partCode,
        keyComposite: dimension.keyComposite,
        format,
        extraDimensions: collectExtraDimensions(spec, specOptions),
      });
      // Trigger the actual browser download
      const a = document.createElement('a');
      a.href = res.url;
      a.download = res.fileName;
      document.body.appendChild(a);
      a.click();
      a.remove();
      setStates((s) => ({ ...s, [format]: { kind: 'done', result: res } }));
    } catch (err) {
      const e = err as {
        response?: { status?: number; data?: { error?: string; message?: string; phase?: string } };
        message?: string;
      };
      const notConfigured =
        e.response?.status === 503 && e.response?.data?.error === 'not_configured';
      setStates((s) => ({
        ...s,
        [format]: {
          kind: 'error',
          message:
            e.response?.data?.message ?? e.message ?? String(err),
          notConfigured,
        },
      }));
    }
  }

  const disabled = !partCode || !dimension;

  return (
    <div className="flex flex-col gap-2 p-3">
      {/* Title + warning row */}
      <div className="flex items-start gap-3">
        <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-gradient-to-br from-brand-500 to-accent-500 text-white shadow-sm">
          <Download className="h-4 w-4" />
        </div>
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-2 text-xs font-semibold text-slate-800">
            {t('download.title')}
            {dimension?.keyComposite && (
              <span className="truncate rounded bg-slate-100 px-1.5 py-0.5 font-mono text-[10px] text-slate-500">
                {dimension.keyComposite}
              </span>
            )}
          </div>
          {disabled ? (
            <div className="text-[10px] text-slate-400">{t('download.nothing')}</div>
          ) : (
            <div
              title={t('download.warningDetail')}
              className="flex items-center gap-1 text-[10px] text-amber-700"
            >
              <AlertTriangle className="h-3 w-3" />
              <span>{t('download.warning')}</span>
            </div>
          )}
        </div>
      </div>

      {/* Buttons — local formats (generated locally) */}
      <div className="flex flex-wrap items-center gap-1.5">
        <span className="text-[9px] font-bold uppercase tracking-wider text-brand-600">
          ★ Local
        </span>
        {LOCAL_FORMATS.map((fmt) => (
          <FormatButton
            key={fmt}
            fmt={fmt}
            state={states[fmt] ?? { kind: 'idle' }}
            disabled={disabled}
            onClick={() => trigger(fmt)}
            variant="local"
          />
        ))}
      </div>

      {/* Buttons — exchanger formats (Phase 2 — 준비 중) */}
      <div className="flex flex-wrap items-center gap-1.5">
        <span className="text-[9px] font-bold uppercase tracking-wider text-slate-400">
          CAD Exchanger
        </span>
        {EXCHANGER_FORMATS.map((fmt) => (
          <FormatButton
            key={fmt}
            fmt={fmt}
            state={states[fmt] ?? { kind: 'idle' }}
            disabled={disabled}
            onClick={() => trigger(fmt)}
            variant="exchanger"
          />
        ))}
      </div>
    </div>
  );
}

function FormatButton({
  fmt,
  state,
  disabled,
  onClick,
  variant,
}: {
  fmt: DownloadFormat;
  state: BtnState;
  disabled: boolean;
  onClick: () => void;
  variant: 'local' | 'exchanger';
}) {
  const { t } = useTranslation();
  const busy = state.kind === 'busy';
  const done = state.kind === 'done';
  const error = state.kind === 'error';
  const notConfigured = error && state.notConfigured;

  // Tooltip reflects current state.
  let title = '';
  if (state.kind === 'done') {
    const kb = (state.result.sizeBytes ?? 0) / 1024;
    title =
      (state.result.fromCache
        ? `${t('download.cached')} · `
        : `${t('download.fresh')} · `) +
      t('download.sizeBytes', { kb: kb.toFixed(1) }) +
      (state.result.generatedMs
        ? ` · ${t('download.generatedMs', { ms: state.result.generatedMs })}`
        : '');
  } else if (state.kind === 'error') {
    title = notConfigured ? t('download.notConfigured') : state.message;
  }

  const colorBase = variant === 'local'
    ? 'border-surface-border bg-white text-slate-700 hover:border-brand-300 hover:bg-brand-50 hover:text-brand-700'
    : 'border-slate-200 bg-slate-50 text-slate-500 hover:border-slate-300 hover:bg-slate-100 hover:text-slate-700';

  return (
    <button
      type="button"
      disabled={disabled || busy}
      onClick={onClick}
      title={title || undefined}
      className={cn(
        'group flex items-center gap-1.5 rounded-lg border px-3 py-1.5 text-[11px] font-semibold shadow-sm transition',
        colorBase,
        'hover:-translate-y-px',
        'disabled:pointer-events-none disabled:opacity-40',
        busy && 'bg-brand-600 text-white border-brand-600 hover:bg-brand-600',
        done && !state.result.fromCache && 'bg-emerald-50 border-emerald-300 text-emerald-800',
        done && state.result.fromCache && 'bg-sky-50 border-sky-300 text-sky-800',
        error && !notConfigured && 'bg-red-50 border-red-300 text-red-700',
        error && notConfigured && 'bg-amber-50 border-amber-200 text-amber-700',
      )}
    >
      {busy && <Loader2 className="h-3.5 w-3.5 animate-spin" />}
      {done && !state.result.fromCache && <Check className="h-3.5 w-3.5" />}
      {done && state.result.fromCache && <Zap className="h-3.5 w-3.5" />}
      {error && !notConfigured && <AlertCircle className="h-3.5 w-3.5" />}
      {error && notConfigured && <AlertTriangle className="h-3.5 w-3.5" />}
      {state.kind === 'idle' && (
        <FileDown className={cn('h-3.5 w-3.5', variant === 'local' ? 'text-brand-600' : 'text-slate-400')} />
      )}
      <span>{fmt}</span>
      {done && (
        <span className="ml-0.5 text-[9px] opacity-75">
          {state.result.fromCache ? t('download.cached') : t('download.fresh')}
        </span>
      )}
      {busy && <span className="text-[9px] opacity-90">{t('download.generating')}</span>}
      {error && notConfigured && (
        <RotateCcw className="h-3 w-3 opacity-60" />
      )}
    </button>
  );
}
